### ISSUE TITLE
Vypracovať katalóg požiadaviek

### ISSUE THREAD

**Issue by ZubatyNos** [TIS2021-FMFI/vytazenie-rampy#1]

**Comment by rackova43** [comment]
Link na zdieľaný dokument: 
https://docs.google.com/document/d/1Cxno-5XYCWX2DlEwosOw-7EgVfMaHrwyr3ngHBUimyE/edit?usp=sharing

**Comment by ZubatyNos** [comment]
Finálna verzia sa už nachádza v docs

**Comment by ZubatyNos** [comment]
Finalna verzia sa nachadza v docs/

**Comment by ZubatyNos** [comment]
Este treba katalog doplnit

**Comment by ZubatyNos** [comment]
Už dúfajme finálna verzia v [docs/](https://github.com/TIS2021-FMFI/vytazenie-rampy/blob/main/docs/KatalogPoziadaviekFINALNY.docx)
